name: Continuos Delivery

on:
  pull_request:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v7
        with:
          name: projeto.zip
          path: |
            meu_projeto.txt
            rotina_castiel.txt
            README.md

  docker:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Baixar os arquivos)
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4