name: Continuos Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Baixa o histórico completo para o Super-Linter saber o que mudou
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest

  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Discord Webhook
        uses: Sniddle/discord-webhook@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          template: |
            {
              "username": "GitHub Actions",
              "embeds": [
                {
                  "title": "Build Status",
                  "description": "The build has completed successfully.",
                  "color": 3066993
                }
              ]
            }
          include_env: true